language: node_js

node_js :
  - "10.15.0"

cache:
directories:
  - "node_modules"

  services:
  - postgresql

before_script:
  - psql -c 'create database Epic-mail;' -U postgres
  - npm run create

script: 
  - npm run test

after_script: 
  - npm run coverage