language: node_js

node_js :
  - "10.15.0"

cache:
directories:
  - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database epic_mail_db;' -U postgres
  - npm run create

script:
  - npm run test

after_script:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build -t "lcov" --exit-code $TRAVIS_TEST_RESULT
  