/**
 * Epic-mail
 * kihvhyivivi
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Localhost3A30011api1v21auth1signupRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object MiscApi {

  /**
   * Sign in a user
   * 
   * Expected answers:
   *   code 200 :  
   * 
   * @param contentType 
   * @param body 
   */
  def signupPost(contentType: String, body: Localhost3A30011api1v21auth1signupRequest): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "http://localhost:3001/api/v2/auth", "/signup", "application/json")
      .withBody(body)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Unit](200)
      

}

