/**
 * Epic-mail
 * kihvhyivivi
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Localhost3001apiv2authsignupRequest (
  firstname: String,
  lastname: String,
  email: String,
  password: String,
  phonenumber: String
) extends ApiModel


